name: Python application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    - name: Test list changes
      run: |
        echo $GITHUB_REPOSITORY
        echo $GITHUB_SHA
        echo $GITHUB_REF
        echo $GITHUB_HEAD_REF
        echo $GITHUB_BASE_REF
        ./test.sh
